<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/24
 * Time: 22:23
 */

namespace backend\Filters;


use yii\base\ActionFilter;

class RbacFilter extends ActionFilter
{
    public function beforeAction($action)
    {
        if(\Yii::$app->user->can($action->uniqueId)){
           $html=<<<HTML
<script >

window.history.go(-1);
</script>


HTML;
           \Yii::$app->session->setFlash("danger",'亲还没有这个权限~~');
           return false;

        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}